server:
  port: ${PORT:5000}

spring:
  main:
    banner-mode: console
  devtools:
    restart:
      additional-paths: ./resources

  mail:
    host: smtp.google.com
    username: mammadzademaryam@gmail.com
    password: secretiba123!
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    data: classpath:/import.sql
  #    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

