insert into currency (curr_name_abv, curr_name_long) VALUES ('EUR','European Union')
insert into currency (curr_name_abv, curr_name_long) VALUES ('USD','American dollar')
insert into currency (curr_name_abv, curr_name_long) VALUES ('CAD','Canadian Dollar')
insert into currency (curr_name_abv, curr_name_long) VALUES ('HKD','Hong Kong Dollar')
insert into currency (curr_name_abv, curr_name_long) VALUES ('ISK','Icelandic Króna')
insert into currency (curr_name_abv, curr_name_long) VALUES ('BGN','Bulgarian Lev')
insert into currency (curr_name_abv, curr_name_long) VALUES ('TRY','European Union')
insert into currency (curr_name_abv, curr_name_long) VALUES ('PHP','Philippine Peso')
insert into currency (curr_name_abv, curr_name_long) VALUES ('GBP','British Pound Sterling')
insert into currency (curr_name_abv, curr_name_long) VALUES ('RUB','Russian Ruble')