insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('EUR','European Union', '€')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('USD','American dollar','$')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('DKK','Danish Krone','Kr.')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('HUF','Hungarian Forint','Ft')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('ISK','Icelandic Króna','kr')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('BGN','Bulgarian Lev','лв.')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('CNY','Chinese Yuan','¥')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('PHP','Philippine Peso','₱')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('GBP','British Pound Sterling','£')
insert into currency (curr_name_abv, curr_name_long, curr_symbol) VALUES ('RUB','Russian Ruble','RUB')